services:
  web:
    build: .
    command: bin/web
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file: .env
  worker:
    build: .
    command: bin/worker
    depends_on:
      - redis
    env_file: .env
  redis:
    image: redis
